# Generated by Django 6.0.5 on 2026-06-30 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('description', models.TextField(verbose_name='Document description')),
                ('file', models.FileField(max_length=255, upload_to='documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'png', 'jpg', 'jpeg', 'gif', 'zip', 'rar', '7z'])], verbose_name='Document file')),
                ('original_filename', models.CharField(editable=False, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('access_code', models.CharField(db_index=True, editable=False, max_length=12, unique=True, verbose_name='Access code')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload date')),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('is_encrypted', models.BooleanField(default=True, help_text='File is encrypted at rest')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-upload_date'],
            },
        ),
    ]
